# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 17:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('genre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('game_name', models.TextField(blank=True)),
                ('genre', models.TextField()),
                ('multiplayer', models.IntegerField(default=0)),
                ('developer', models.TextField()),
                ('publisher', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('platform_name', models.TextField(blank=True)),
                ('manufacturer', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('region_name', models.TextField(blank=True)),
                ('format', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'PAL'), (2, 'NTSC-U'), (3, 'NTSC-J'), (4, 'NTSC-C')], default=1, verbose_name='format ')),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rating', models.PositiveSmallIntegerField(choices=[(0, 'zero'), (1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3, verbose_name='Rating (stars)')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('region_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='mygames.Region')),
                ('platform_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='mygames.Platform')),
                ('game_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mygames.Game')),
                ('release_date', models.DateField(default=datetime.date(2017, 4, 20))),
            ],
            bases=('mygames.game', 'mygames.platform', 'mygames.region'),
        ),
        migrations.AddField(
            model_name='userrating',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mygames.Game'),
        ),
        migrations.AddField(
            model_name='platform',
            name='games',
            field=models.ManyToManyField(to='mygames.Game'),
        ),
        migrations.AddField(
            model_name='accesory',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mygames.Platform'),
        ),
    ]
